# Python Tutorial: Using `os` and `pandas`
**With R comparisons and inclusive language!**

## Part 1 — Basic File Operations with `os`
### 1. Check working directory

In [1]:
import os
os.getcwd()

'/Users/zzanescott/Desktop/DS1'

### 2. List files

In [2]:
os.listdir('.')

['run3_temp.txt',
 'run2_temp.txt',
 '10_14_Logic_Puzzles.html',
 'os_pandas_tutorial.ipynb',
 '.DS_Store',
 '002_TU_Containers.html',
 '10_23_Functions.html',
 'notes.txt',
 'run2_accel.txt',
 '10_21_Packages.ipynb',
 '10_2_For_Loops.ipynb',
 'spock.py',
 '002_TU_Containers.ipynb',
 'ZS_9_16_containers.html',
 'example_data',
 '10_30_Monty_Hall.ipynb',
 'Index_methods.ipynb',
 '10_14_Logic_Puzzles.ipynb',
 'demo_backup.txt',
 'pillowfight_puzzles.ipynb',
 'ZS_Operators.html',
 'temperatures.csv',
 '10_30_Monty_Hall.html',
 'run3_accel.txt',
 'ZS_Index_methods.html',
 '004_TU_For_Iterables_ListComp.ipynb',
 '004_HW_For_Iterables_ListComp.md',
 '10_2_for_loops.html',
 'TU_introToBasicPython.ipynb',
 'class_example.ipynb',
 'run1_temp.txt',
 'ZS_Submission_HW_VarsAndOps.html',
 'HW_VarsAndOps.ipynb',
 'pillowfight_puzzles.html',
 '003_TU_IndexingAndMethods.ipynb',
 '10_12_Operators.ipynb',
 '10_23_Functions.ipynb',
 '10_21_Packages.html',
 'run1_accel.txt',
 '9_16_containers.ipynb']

### 3. Change directories

In [3]:
os.chdir('example_data')
os.getcwd()

'/Users/zzanescott/Desktop/DS1/example_data'

### 4. Rename/move a file

In [4]:
with open('demo.txt','w') as f: f.write('hello!\n')
os.rename('demo.txt','demo_backup.txt')

### 5. On your own!

In [5]:
# print the contents of the file you just renamed
file_path = 'demo_backup.txt' 
other_file_path = 'demo.txt'

# Open the file in read mode ('r')
with open(file_path, 'r') as file:
    # Read the entire content of the file
    file_content = file.read()
   # Print the content to the console
    print(file_content)

# show whether or not the original file, "demo.txt" still exists
with open(file_path, 'r') as file:
    # Read the entire content of the file
    file_content = file.read()
   # Print the content to the console
    print(file_content)

# If it doesn't, can you restore it by copying from "demo_backup.txt"?
#isn't needed, the file was able to be opened

hello!

hello!

## Part 2 — `pandas` for Data Analysis
### Read a CSV

In [6]:
import pandas as pd
df = pd.read_csv('temperatures.csv')
df

   run  temp
0    1  22.8
1    2  23.1
2    3  21.9

### Compute stats

In [7]:
df['temp'].mean(), df['temp'].min(), df['temp'].max()

(22.600000000000005, 21.9, 23.1)

### Add column

In [8]:
df['temp_F'] = df['temp']*9/5+32
df

   run  temp  temp_F
0    1  22.8   73.04
1    2  23.1   73.58
2    3  21.9   71.42

### On your own

In [14]:
# Compute the average temperature in Fahrenheit
meanF = df['temp_F'].mean()
print(meanF)
# Save this average temperature to a new file, "average_temp.txt"
with open("average_temp.txt", "w") as file:
    file.write(str(meanF))

72.68

## Putting it all together
Load multiple text files, build a DataFrame, summarize, and save.

In [15]:
import glob
import pandas as pd
import os

# Check out the `glob` module to see how it works
# It lets you find files matching a pattern
# For example, to find all the .csv files in the current directory:
csv_files = glob.glob('*.csv')
csv_files

['temperatures.csv']